[build]
  # Build command for the frontend
  command = "npm run build:netlify"
  
  # Publish directory (frontend build output)
  publish = "dist/public"
  
  # Functions directory (backend serverless functions)
  functions = "netlify/functions"

[build.environment]
  # Set Node.js version
  NODE_VERSION = "18"

# Redirect all API calls to serverless functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 